name: Docker Image CI

on:
  push:
    branches: [ "master", "prod" ]
  pull_request:
    branches: [ "master", "prod" ]

env:
  TG_USER_ID: ${{vars.TG_API_KEY}}
  TG_API_KEY: ${{vars.TG_API_KEY}}  
  DATABASE_HOST: ${{vars.DATABASE_HOST}}  
  DATABASE_NAME: ${{vars.DATABASE_NAME}}  
  DATABASE_PASS: ${{vars.DATABASE_PASS}}  
  DATABASE_PORT: ${{vars.DATABASE_PORT}}  
  DATABASE_USER: ${{vars.DATABASE_USER}}  
  SECRET_KEY: ${{vars.SECRET_KEY}}  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile
